name: github-action-practice
run-name: ${{ github.actor }} - GitHub Actions
on:
  push:
    branches:
      - master
jobs: 
  congrats-on-pushing:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration 
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - run: echo "Congrats ${{ github.actor }}" >> log.txt
      - run: date >> log.txt
      - run: | 
          git config --global user.name "Jaineel Doshi" 
          git config --global user.email "Jaineel.Doshi@fgsglobal.com"
          git add -A
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

