name: Continuous Integration 

on:
  push:
    branches:
      - master


jobs: 
  congrats-on-pushing:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - uses: actions/checkout@v3
      - run: touch "congrats.txt"
#      - run: echo ${{ github.actor }} >> congrats.txt
#      - run: echo "hello" >> congrats.txt
#	run:  
#	  git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
#         git config --global user.email "username@users.noreply.github.com"
      - run: git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      - run: git push
